# Generated by Django 5.2 on 2025-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=100, verbose_name='dis')),
                ('rate', models.IntegerField(verbose_name='rate')),
                ('time', models.IntegerField(verbose_name='time')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='pub')),
            ],
        ),
    ]
