# Generated by Django 5.2 on 2025-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='test_field',
            field=models.BooleanField(default=False),
        ),
    ]
