# Generated by Django 5.2 on 2025-04-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='food',
            name='discription',
            field=models.CharField(max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='food',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(verbose_name='زمان پخت'),
        ),
    ]
