# Generated by Django 5.2 on 2025-04-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_food_test_field_alter_food_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='foods/'),
        ),
    ]
