# Generated by Django 5.2 on 2025-04-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('B', 'صبحانه'), ('DI', 'ناهار'), ('L', 'شام'), ('D', 'نوشیدنی')], default='D', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
