# Generated by Django 5.2 on 2025-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakefast', 'صبحانه'), ('dinner', 'ناهار'), ('lunch', 'شام'), ('drinks', 'نوشیدنی')], default='drinks', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
