# Generated by Django 5.2 on 2025-04-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_alter_food_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='زمان پخت'),
        ),
    ]
